workflows:
  ios-webview-app:
    name: iOS WebView App
    platform: ios
    flutter:
      channel: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --no-codesign
